### PR TITLE
Pull request for the NY Times project on Microverse HTML & CSS3 Course

### PR DESCRIPTION
**Pull request by Stricks1**
We want to comment that we used a lot of child selectors on the CSS for the practice of different kinds of selectors.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, the project looks great and awesome 🙂 You deserve 🎖 . However, let us improve our code be making a few changes. Kindly address the comments below:
* We did some refactoring and that's great, however, there is more to do. Let us apply the DRY rule and in the example image below:
tw
* Currently, the footer is not fixed. It should be as the nav
ftt
* The README needs improvements. We can add more of the social media handles and our emails. Let us check [this template](https://github.com/microverseinc/readme-template)

Kindly make these changes and submit another code review 🙂 
Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Comment by Stricks1** [comment]
> ## Status: Require changes recycle traffic_light
> 
> Hi **TEAM**, the project looks great and awesome slightly_smiling_face You deserve medal_military . However, let us improve our code be making a few changes. Kindly address the comments below:
> 
>     * We did some refactoring and that's great, however, there is more to do. Let us apply the DRY rule and in the example image below:
>       tw
> 
>     * Currently, the footer is not fixed. It should be as the nav
>       ftt
> 
>     * The README needs improvements. We can add more of the social media handles and our emails. Let us check [this template](https://github.com/microverseinc/readme-template)
> 
> 
> Kindly make these changes and submit another code review slightly_smiling_face
> Happy coding_ man_technologist
> [Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

We created the footer fixed, applied more DRY rules on the CSS file and added more personal information on the README file.

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :+1: 

Hi @Stricks1 and @asiimwedismas :smile: :smile: 
You guys did the required changes asked by Daniel(TSE) and your project was approved :100: 
Before merging it into master, can you please do the following changes:


:v: Can you please update your live version? The required changes that you guys did aren't on there.
:v: Can you please add more contact info of Dismas, on the readme? :smile_cat: 

**SUGGESTION FOR THE NEXT PROJECTS:**

You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''youtube-page'' instead of ''feature-branch', for example. It will be more descriptive.



If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: 

Project reviewed by Thaís Vieira (TSE)

**Comment by asiimwedismas** [comment]
> ### **STATUS: PROJECT APPROVED** 👍
> Hi @Stricks1 and @asiimwedismas 😄 😄
> You guys did the required changes asked by Daniel(TSE) and your project was approved 💯
> Before merging it into master, can you please do the following changes:
> 
> ✌️ Can you please update your live version? The required changes that you guys did aren't on there.
> ✌️ Can you please add more contact info of Dismas, on the readme? 😸
> 
> **SUGGESTION FOR THE NEXT PROJECTS:**
> 
> You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''youtube-page'' instead of ''feature-branch', for example. It will be more descriptive.
> 
> If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)
> 
> ### **Happy coding and good luck on the next project** 💻
> Project reviewed by Thaís Vieira (TSE)

Added more contact info for Dismas and updated the live demo link

**Pull request merged**
